env:
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 9
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  prettier/prettier:
    - error
    - endOfLine: auto
  @typescript-eslint/no-var-requires: 0
